Started by user Pavel Svitov
Running as SYSTEM
Building remotely on agent-01 (centos ansible) in workspace /opt/jenkins_agent/workspace/freestyle-molecule
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /opt/jenkins_agent/workspace/freestyle-molecule/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/psvitov/mnt_homework_8_5.git # timeout=10
Fetching upstream changes from https://github.com/psvitov/mnt_homework_8_5.git
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
 > git fetch --tags --progress https://github.com/psvitov/mnt_homework_8_5.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision 4d49423665ab9317110078795c91d10c82e4a2e5 (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 4d49423665ab9317110078795c91d10c82e4a2e5 # timeout=10
Commit message: "Update molecule.yml"
 > git rev-list --no-walk 4d49423665ab9317110078795c91d10c82e4a2e5 # timeout=10
[freestyle-molecule] $ /bin/sh -xe /tmp/jenkins768267303665880610.sh
+ cd /opt/jenkins_agent/workspace/freestyle-molecule/roles/vector-role/
+ whoami
jenkins
+ docker --version
Docker version 20.10.17, build 100c701
+ molecule --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible-config", line 34, in <module>
    from ansible import context
ModuleNotFoundError: No module named 'ansible'
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/jenkins/.local/lib/python3.9/site-packages/click/core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "/home/jenkins/.local/lib/python3.9/site-packages/molecule/shell.py", line 63, in print_version
    runtime = Runtime()
  File "/home/jenkins/.local/lib/python3.9/site-packages/ansible_compat/runtime.py", line 93, in __init__
    self.config = AnsibleConfig()
  File "/home/jenkins/.local/lib/python3.9/site-packages/ansible_compat/config.py", line 422, in __init__
    config_dump = subprocess.check_output(
  File "/usr/local/python3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/python3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ansible-config', 'dump']' returned non-zero exit status 1.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
